services:
  app:
    build: .
    container_name: itlabbd-app
    restart: unless-stopped
    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - redis

    environment:
      NODE_ENV: production

      DATABASE_URL: postgresql://itlabbd:StrongPassword123@postgres:5432/itlabbd?schema=public
      REDIS_URL: redis://redis:6379

      ADMIN_USERNAME: admin

      ADMIN_PASSWORD_HASH: '$$2b$$12$$irCVubHLi7uF7zvnl7eLQ.H7u/2Bha3RyAiVEvlgQl7u2oF67KUBe'

      ALLOW_ENV_AUTH_FALLBACK: "true"

      SESSION_SECRET: Q8x7M2nK9pL4vR6tY1wZ5cA8eD3fG7hJ2mN9pQ4rT6uV8xY3zB5cD7eF

  postgres:
    image: postgres:16
    container_name: itlabbd-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: itlabbd
      POSTGRES_USER: itlabbd
      POSTGRES_PASSWORD: StrongPassword123

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: itlabbd-redis
    restart: unless-stopped

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: