services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3010:3000"

    depends_on:
      - postgres
      - redis

    environment:
      NODE_ENV: production

      DATABASE_URL: postgresql://codexman:StrongPassword123@postgres:5432/codexman?schema=public
      REDIS_URL: redis://redis:6379

      ADMIN_USERNAME: admin
      ALLOW_ENV_AUTH_FALLBACK: "false"
      ADMIN_FORCE_PASSWORD_SYNC: "false"

      SESSION_SECRET: Q8x7M2nK9pL4vR6tY1wZ5cA8eD3fG7hJ2mN9pQ4rT6uV8xY3zB5cD7eF
      ANALYTICS_HASH_SECRET: Q7mX9kLp3vR8sT2wY6zA1cD4eF5gH7jK9nP2qR6u

      NEXT_PUBLIC_SITE_URL: https://dev.codexman.com
      SITE_URL: https://dev.codexman.com

      PG_DUMP_PATH: /usr/bin/pg_dump
      PG_RESTORE_PATH: /usr/bin/pg_restore
      BACKUP_DIR: /app/storage/backups

      CMS_QUERY_TIMEOUT_MS: "4000"
      CMS_SEO_QUERY_TIMEOUT_MS: "1200"
      CMS_CACHE_TTL_SECONDS: "60"
      CMS_FALLBACK_CACHE_TTL_SECONDS: "15"
      CMS_DEBUG_TIMING: "false"

    volumes:
      - itlabbd_uploads:/app/storage/uploads
      - itlabbd_downloads:/app/storage/downloads
      - itlabbd_backups:/app/storage/backups

  postgres:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_DB: codexman
      POSTGRES_USER: codexman
      POSTGRES_PASSWORD: StrongPassword123

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  itlabbd_uploads:
  itlabbd_downloads:
  itlabbd_backups: