import Link from "next/link"
import { prisma } from "@/lib/prisma"
import { Activity, Building2, CalendarDays, CalendarRange, Eye, FolderKanban, Mail, MonitorPlay, ShieldCheck, TrendingUp } from "lucide-react"
import { startOfUtcMonth, startOfUtcWeek, startOfUtcYear, uniqueVisitorsSince, utcDateKey } from "@/lib/visitor-analytics"
export const dynamic = "force-dynamic"
async function safeCount(factory: () => Promise<number>) { try { return await factory() } catch { return 0 } }
export default async function Dashboard() {
  const [services, projects, demos, leads, newLeads, logos, today, weekly, monthly, yearly] = await Promise.all([
    safeCount(() => prisma.service.count()), safeCount(() => prisma.portfolio.count()), safeCount(() => prisma.demo.count()), safeCount(() => prisma.contactLead.count()), safeCount(() => prisma.contactLead.count({ where: { status: "NEW" } })), safeCount(() => prisma.companyLogo.count()), safeCount(() => prisma.visitorDaily.count({ where: { dateKey: utcDateKey() } })), safeCount(() => uniqueVisitorsSince(startOfUtcWeek())), safeCount(() => uniqueVisitorsSince(startOfUtcMonth())), safeCount(() => uniqueVisitorsSince(startOfUtcYear())),
  ])
  const stats = [
    { label: "Services", value: services, icon: Building2, href: "/admin/services", hint: "Manage service cards" },
    { label: "Portfolio Projects", value: projects, icon: FolderKanban, href: "/admin/portfolios", hint: "Edit project case studies" },
    { label: "Demo Items", value: demos, icon: MonitorPlay, href: "/admin/demos", hint: "Manage showcase demos" },
    { label: "Contact Leads", value: leads, icon: Mail, href: "/admin/leads", hint: newLeads ? `${newLeads} new lead${newLeads === 1 ? "" : "s"}` : "Open lead inbox" },
    { label: "Trusted Logos", value: logos, icon: ShieldCheck, href: "/admin/logos", hint: "Manage company logos" },
  ]
  const visitors = [{ label: "Today", value: today, icon: Eye }, { label: "This week", value: weekly, icon: CalendarDays }, { label: "This month", value: monthly, icon: CalendarRange }, { label: "This year", value: yearly, icon: TrendingUp }]
  return <div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Dashboard</p><h1 className="mt-1 font-heading text-3xl font-bold">Website overview</h1><p className="mt-3 text-muted-foreground">Manage the public website and monitor private traffic from one focused workspace.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map(stat => <Link href={stat.href} key={stat.label} className="group cursor-pointer rounded-2xl border border-border bg-card p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg hover:shadow-blue-900/5"><stat.icon className="size-7 text-primary transition duration-300 group-hover:scale-110" /><p className="mt-5 font-heading text-3xl font-bold">{stat.value}</p><p className="mt-1 text-sm font-semibold text-slate-700">{stat.label}</p><p className="mt-2 text-xs text-muted-foreground">{stat.hint}</p></Link>)}</div><Link href="/admin/analytics" className="mt-8 block cursor-pointer rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:border-blue-200 hover:shadow-lg"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Private analytics</p><h2 className="mt-1 font-heading text-xl font-bold">Website visitors</h2></div><span className="text-sm font-bold text-blue-700">Open analytics →</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{visitors.map(item => <div key={item.label} className="rounded-2xl bg-slate-50 p-4"><item.icon className="size-5 text-blue-700" /><p className="mt-3 font-heading text-2xl font-bold">{item.value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{item.label}</p></div>)}</div></Link><section className="mt-8 rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-3"><Activity className="text-primary" /><h2 className="font-heading text-xl font-bold">CMS status</h2></div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Homepage data, services, global marketplaces, portfolio projects, testimonials, logos, leads, media, analytics and SEO records are managed through the custom CMS. Redis caching is invalidated after admin changes.</p></section></div>
}
