"use client"
import Image from "next/image"
import Link from "next/link"
import { ArrowRight } from "lucide-react"
import { useMemo, useState } from "react"
type Project = { slug: string; title: string; imageUrl: string; category: string; buttonLabel?: string | null; buttonUrl?: string | null }
export function PortfolioSection({ projects, content }: { projects: Project[]; content?: Record<string, unknown> }) {
  const eyebrow = typeof content?.eyebrow === "string" ? content.eyebrow : "Latest Projects"
  const headline = typeof content?.headline === "string" ? content.headline : "Some of Our Web Design Sample List"
  const subtitle = typeof content?.subtitle === "string" ? content.subtitle : "Selected work created to support trust, clarity and business growth."
  const exploreLabel = typeof content?.buttonLabel === "string" ? content.buttonLabel : "Explore Full Portfolio"
  const exploreUrl = typeof content?.buttonUrl === "string" ? content.buttonUrl : "/portfolio"
  const filters = useMemo(() => ["All", ...Array.from(new Set(projects.map(p => p.category)))], [projects])
  const [active, setActive] = useState("All")
  const filtered = active === "All" ? projects : projects.filter(p => p.category === active)
  return <section id="portfolio" className="bg-white py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><div className="text-center"><span className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">{eyebrow}</span><h2 className="mt-3 font-heading text-3xl font-bold text-foreground md:text-5xl">{headline}</h2><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{subtitle}</p></div><div className="mt-8 flex flex-wrap items-center justify-center gap-3">{filters.map(filter => <button key={filter} onClick={() => setActive(filter)} className={`cursor-pointer rounded-full px-5 py-2.5 text-sm font-semibold transition duration-200 ${active === filter ? "bg-blue-700 text-white shadow-md" : "border border-slate-200 bg-white text-muted-foreground hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"}`}>{filter}</button>)}</div><div className="mt-10 grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(project => { const href = project.buttonUrl || `/portfolio/${project.slug}`; const label = project.buttonLabel || "View project"; return <Link href={href} key={project.slug} className="group relative cursor-pointer overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-2 hover:border-blue-200 hover:shadow-xl"><Image src={project.imageUrl || "/placeholder.svg"} alt={project.title} width={900} height={675} className="aspect-[4/3] w-full object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width:768px) 100vw, 33vw" /><div className="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-slate-950/90 via-slate-950/25 to-transparent p-7 opacity-0 transition-opacity duration-300 group-hover:opacity-100"><h3 className="font-heading text-xl font-semibold text-white">{project.title}</h3><p className="mt-1 text-sm text-sky-100">{project.category}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-white">{label}<ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></div></Link> })}</div><div className="mt-10 text-center"><Link href={exploreUrl} className="brand-button inline-flex items-center gap-2 rounded-xl px-7 py-3.5 text-sm font-bold text-white">{exploreLabel}<ArrowRight className="size-4" /></Link></div></div></section>
}
