import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Briefcase, Building2, Code2, Lightbulb, Newspaper, Search, Server, ShoppingBag, type LucideIcon } from "lucide-react"
const iconMap: Record<string, LucideIcon> = { Briefcase, Building2, Code2, Lightbulb, Newspaper, Search, Server, ShoppingBag }
const iconStyles = ["bg-blue-50 text-blue-700", "bg-sky-50 text-sky-700", "bg-emerald-50 text-emerald-700", "bg-amber-50 text-amber-700"]
type Service = { slug: string; title: string; excerpt: string; icon?: string | null; content?: unknown }
function record(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {} }
export function ServicesSection({ services, content }: { services: Service[]; content?: Record<string, unknown> }) {
  const eyebrow = typeof content?.eyebrow === "string" ? content.eyebrow : "Our services"
  const headline = typeof content?.headline === "string" ? content.headline : "We run all kinds Service"
  const subtitle = typeof content?.subtitle === "string" ? content.subtitle : "Choose the digital service that fits your next business goal."
  return <section id="services" className="bg-slate-50 py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><div className="text-center"><span className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">{eyebrow}</span><h2 className="mt-3 font-heading text-3xl font-bold text-foreground md:text-5xl">{headline}</h2><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{subtitle}</p></div><div className="mt-11 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{services.map((service, index) => { const Icon = iconMap[service.icon || ""] || Code2; const data = record(service.content); const href = typeof data.buttonUrl === "string" && data.buttonUrl ? data.buttonUrl : `/services/${service.slug}`; const label = typeof data.buttonLabel === "string" && data.buttonLabel ? data.buttonLabel : "View More"; const cardImage = typeof data.cardImage === "string" ? data.cardImage : ""; const iconImage = typeof data.iconImage === "string" ? data.iconImage : ""; return <Link id={service.slug} key={service.slug} href={href} className="group relative cursor-pointer overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-2 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-900/5">{cardImage && <div className="overflow-hidden"><Image src={cardImage} alt={service.title} width={760} height={440} className="aspect-[16/9] w-full object-cover transition duration-700 group-hover:scale-105" /></div>}<div className="p-7"><span className={`relative flex size-16 items-center justify-center overflow-hidden rounded-2xl ${iconStyles[index % iconStyles.length]} transition duration-300 group-hover:scale-105`}>{iconImage ? <Image src={iconImage} alt={`${service.title} icon`} width={48} height={48} unoptimized={iconImage.toLowerCase().endsWith(".svg")} className="size-11 object-contain" /> : <Icon className="size-8" />}</span><h3 className="relative mt-5 font-heading text-xl font-semibold text-foreground">{service.title}</h3><p className="relative mt-3 text-sm leading-relaxed text-muted-foreground">{service.excerpt}</p><span className="relative mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700">{label}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></div></Link> })}</div></div></section>
}
