"use client"
import Image from "next/image"
import { ChevronLeft, ChevronRight, Star } from "lucide-react"
import { useState } from "react"
type Testimonial = { id: string; brand: string; brandImageUrl?: string | null; clientImageUrl?: string | null; quote: string; author: string; position?: string | null; rating: number }
export function TestimonialsSection({ testimonials, content }: { testimonials: Testimonial[]; content?: Record<string, unknown> }) {
  const eyebrow = typeof content?.eyebrow === "string" ? content.eyebrow : "User Feedback"
  const headline = typeof content?.headline === "string" ? content.headline : "We love our Clients & they Love us."
  const subtitle = typeof content?.subtitle === "string" ? content.subtitle : "Real feedback from clients who trusted IT Lab BD with their digital growth."
  const requested = Number(content?.displayCount || 3)
  const displayCount = Math.max(1, Math.min(testimonials.length, Number.isFinite(requested) ? requested : 3))
  const [index, setIndex] = useState(0)
  if (!testimonials.length) return null
  const visible = Array.from({ length: displayCount }, (_, position) => testimonials[(index + position) % testimonials.length])
  return <section className="bg-slate-50 py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><div className="grid items-center gap-9 xl:grid-cols-[.52fr_1.48fr]"><div><span className="inline-flex items-center gap-3 rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-700 shadow-sm"><i className="size-3 rounded-full bg-sky-500" />{eyebrow}<i className="size-3 rounded-full bg-sky-500" /></span><h2 className="mt-5 max-w-md font-heading text-4xl font-bold leading-tight text-foreground md:text-5xl">{headline}</h2><p className="mt-3 max-w-md text-base leading-7 text-muted-foreground">{subtitle}</p><div className="mt-6 flex gap-3"><button onClick={() => setIndex(index === 0 ? testimonials.length - 1 : index - 1)} aria-label="Previous testimonial" className="flex size-12 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white text-sky-600 shadow-sm transition hover:border-blue-200 hover:bg-blue-50"><ChevronLeft /></button><button onClick={() => setIndex((index + 1) % testimonials.length)} aria-label="Next testimonial" className="flex size-12 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white text-sky-600 shadow-sm transition hover:border-blue-200 hover:bg-blue-50"><ChevronRight /></button></div></div><div className={`grid gap-4 ${displayCount >= 3 ? "md:grid-cols-2 xl:grid-cols-3" : displayCount === 2 ? "sm:grid-cols-2" : "max-w-xl"}`}>{visible.map((item, position) => <article key={`${item.id}-${position}`} className="rounded-3xl border border-slate-200 bg-white p-5 text-center shadow-sm"><div className="flex min-h-9 items-center justify-center">{item.brandImageUrl ? <Image src={item.brandImageUrl} alt={item.brand} width={140} height={40} className="max-h-9 w-auto object-contain" /> : <p className="font-heading text-lg font-bold">{item.brand}</p>}</div><div className="my-3 h-px bg-slate-200" /><p className="text-sm leading-6 text-muted-foreground">“{item.quote}”</p><div className="mt-4 flex justify-center gap-1 text-amber-400">{Array.from({ length: Math.max(0, Math.min(5, item.rating || 5)) }).map((_, i) => <Star key={i} className="size-4 fill-current" />)}</div><div className="mt-4 flex items-center justify-center gap-3">{item.clientImageUrl ? <Image src={item.clientImageUrl} alt={item.author} width={42} height={42} className="size-10 rounded-full object-cover" /> : <span className="flex size-10 items-center justify-center rounded-full bg-blue-50 font-bold text-blue-700">{item.author.slice(0, 1)}</span>}<div className="text-left"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-900">{item.author}</p>{item.position && <p className="mt-1 text-xs text-muted-foreground">{item.position}</p>}</div></div></article>)}</div></div></div></section>
}
