import { Briefcase, Building2, Code2, Handshake, Home, Layers, Lightbulb, Newspaper, Plane, Scale, Search, Server, Shirt, ShoppingCart, Stethoscope, Store, Users, type LucideIcon } from "lucide-react"
const iconMap: Record<string, LucideIcon> = { Briefcase, Building2, Code2, Handshake, Home, Layers, Lightbulb, Newspaper, Plane, Scale, Search, Server, Shirt, ShoppingCart, Stethoscope, Store, Users }
const fallbackItems = [{ icon: "ShoppingCart", label: "Ecommerce" }, { icon: "Newspaper", label: "Newspaper" }, { icon: "Home", label: "Real Estate" }, { icon: "Plane", label: "Tour & Travel" }, { icon: "Store", label: "Buying House" }, { icon: "Layers", label: "Multivendor" }, { icon: "Briefcase", label: "Portfolio" }, { icon: "Stethoscope", label: "Hospital" }, { icon: "Shirt", label: "Fashion" }, { icon: "Scale", label: "Law Firm" }, { icon: "Handshake", label: "B2B & B2C" }, { icon: "Users", label: "Consultancy" }]
const styles = ["border-blue-200/80 bg-white/85 text-blue-700", "border-sky-200/80 bg-white/85 text-sky-700", "border-emerald-200/80 bg-white/85 text-emerald-700", "border-amber-200/80 bg-white/85 text-amber-700", "border-violet-200/80 bg-white/85 text-violet-700", "border-rose-200/80 bg-white/85 text-rose-700"]
function items(value: unknown) { return Array.isArray(value) ? value.map((item: any) => ({ icon: String(item?.icon || "Code2"), label: String(item?.label || "") })).filter(item => item.label).slice(0, 24) : fallbackItems }
export function WhatWeDoSection({ content }: { content?: Record<string, unknown> }) {
  const eyebrow = typeof content?.eyebrow === "string" ? content.eyebrow : "Industry solutions"
  const headline = typeof content?.headline === "string" ? content.headline : "What We Actually Do"
  const subtitle = typeof content?.subtitle === "string" ? content.subtitle : "Focused digital experiences for industries where performance, trust and clarity matter."
  const cards = items(content?.items)
  return <section className="relative overflow-hidden bg-[linear-gradient(135deg,#edf6ff_0%,#eefbff_42%,#f7f3ff_100%)] py-20"><div className="absolute -left-28 top-8 size-72 rounded-full bg-sky-200/35 blur-3xl" /><div className="absolute -right-20 bottom-0 size-72 rounded-full bg-violet-200/35 blur-3xl" /><div className="relative mx-auto max-w-[1760px] px-6 lg:px-10"><div className="text-center"><span className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">{eyebrow}</span><h2 className="mt-3 font-heading text-3xl font-bold text-foreground md:text-5xl">{headline}</h2><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{subtitle}</p></div><div className="mt-11 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">{cards.map((item, index) => { const Icon = iconMap[item.icon] || Code2; return <div key={`${item.icon}-${item.label}`} className={`group flex flex-col items-center gap-3 rounded-2xl border p-6 text-center shadow-sm backdrop-blur transition duration-300 hover:-translate-y-1.5 hover:shadow-xl ${styles[index % styles.length]}`}><span className="flex size-14 items-center justify-center rounded-2xl bg-white shadow-sm ring-1 ring-slate-100 transition duration-300 group-hover:scale-105"><Icon className="size-7" /></span><span className="text-xs font-bold uppercase tracking-wide text-slate-700">{item.label}</span></div> })}</div></div></section>
}
