export type ServiceContent = {
  heroImage: string
  intro: string
  details: string
  additionalImages: string[]
  highlights?: string[]
  layout?: "standard" | "reverse" | "spotlight"
  cardImage?: string
  buttonLabel?: string
  buttonUrl?: string
  ctaLabel?: string
  ctaUrl?: string
}

export const defaultServices = [
  { slug: "business-website", title: "Business Website", excerpt: "Professional websites engineered to build trust, generate leads and support long-term growth.", icon: "Building2", content: { heroImage: "/images/portfolio-1.png", intro: "A strong business website is your digital sales representative. We build clean, fast and credible websites that explain your value clearly and turn visits into qualified enquiries.", details: "Every page is planned around trust, performance and conversion. The result is a responsive website that is easy to manage and ready for future marketing campaigns.", additionalImages: ["/images/about-1.png", "/images/portfolio-5.png", "/images/portfolio-3.png"], highlights: ["Conversion-focused structure", "Mobile-first responsive UI", "SEO-ready foundation"], layout: "standard" } },
  { slug: "portfolio-website", title: "Portfolio Website", excerpt: "Elegant personal and agency portfolio experiences that turn expertise into opportunities.", icon: "Briefcase", content: { heroImage: "/images/portfolio-2.png", intro: "Your portfolio should do more than display screenshots. It should communicate your personality, capabilities and the quality of your work within seconds.", details: "We create refined portfolio experiences for developers, designers, agencies and professionals who need to stand out in competitive international markets.", additionalImages: ["/images/portfolio-2.png", "/images/portfolio-5.png", "/images/about-2.png"], highlights: ["Personal brand storytelling", "Project case studies", "Smooth interactions"], layout: "reverse" } },
  { slug: "e-commerce-website", title: "E-Commerce Website", excerpt: "Secure, conversion-focused online stores with smooth shopping and payment experiences.", icon: "ShoppingBag", content: { heroImage: "/images/portfolio-4.png", intro: "We build e-commerce websites designed for real transactions: clear products, fast navigation, secure checkout and an admin experience your team can actually use.", details: "From catalogue architecture to payment integration and performance optimization, every layer is prepared for sustainable online growth.", additionalImages: ["/images/portfolio-4.png", "/images/portfolio-1.png", "/images/about-1.png"], highlights: ["Product catalogue management", "Secure checkout flow", "Performance optimization"], layout: "spotlight" } },
  { slug: "news-portal", title: "News Portal", excerpt: "Fast and scalable publishing platforms for editorial teams and growing audiences.", icon: "Newspaper", content: { heroImage: "/images/portfolio-3.png", intro: "Publishing platforms need speed, structure and a smooth editorial workflow. We design news portals that help readers discover content without slowing down your team.", details: "Category architecture, search, mobile readability and scalable content management are integrated from the beginning.", additionalImages: ["/images/portfolio-3.png", "/images/portfolio-6.png", "/images/about-2.png"], highlights: ["Editorial CMS", "Category-based navigation", "Fast mobile reading"], layout: "standard" } },
  { slug: "custom-web-development", title: "Custom Web Development", excerpt: "Tailored platforms, dashboards and integrations for complex business requirements.", icon: "Code2", content: { heroImage: "/images/portfolio-6.png", intro: "When an off-the-shelf template is not enough, we build a solution around your workflow, data and business goals.", details: "Dashboards, portals, automations and API integrations are developed with maintainable architecture and clear deployment processes.", additionalImages: ["/images/portfolio-6.png", "/images/portfolio-3.png", "/images/portfolio-2.png"], highlights: ["Custom workflows", "API integrations", "Maintainable architecture"], layout: "reverse" } },
  { slug: "server-management", title: "Server Management", excerpt: "Reliable hosting, deployment, monitoring and maintenance for stable digital products.", icon: "Server", content: { heroImage: "/images/about-2.png", intro: "A polished frontend still needs a reliable home. We help configure, deploy and maintain servers so your applications remain stable and accessible.", details: "Our approach covers environment setup, deployment support, backups, monitoring and practical security hardening.", additionalImages: ["/images/about-2.png", "/images/portfolio-3.png", "/images/about-1.png"], highlights: ["Deployment support", "Monitoring and backups", "Security hardening"], layout: "spotlight" } },
  { slug: "seo-services", title: "SEO Services", excerpt: "Technical and content-focused optimization to improve visibility and qualified traffic.", icon: "Search", content: { heroImage: "/images/portfolio-5.png", intro: "SEO works best when it is built into the website instead of added as an afterthought. We improve the technical foundation and help structure content for visibility.", details: "The work focuses on crawlability, metadata, page structure, speed and clear content opportunities that can attract qualified traffic over time.", additionalImages: ["/images/portfolio-5.png", "/images/portfolio-1.png", "/images/about-1.png"], highlights: ["Technical SEO", "On-page optimization", "Performance audits"], layout: "standard" } },
  { slug: "it-consultancy", title: "IT Consultancy", excerpt: "Clear technology guidance for planning, modernization and smarter digital investment.", icon: "Lightbulb", content: { heroImage: "/images/about-1.png", intro: "Technology decisions should support the business instead of creating unnecessary complexity. We help evaluate options and choose a practical route forward.", details: "From architecture planning to modernization and deployment strategy, the focus remains on clarity, cost control and maintainability.", additionalImages: ["/images/about-1.png", "/images/about-2.png", "/images/portfolio-6.png"], highlights: ["Technology planning", "Architecture review", "Practical roadmaps"], layout: "reverse" } },
] satisfies Array<{ slug: string; title: string; excerpt: string; icon: string; content: ServiceContent }>

export const defaultProjects = [
  { slug: "virtual-reality-app", title: "App for Virtual Reality", category: "Corporate", imageUrl: "/images/portfolio-1.png", excerpt: "A premium product presentation experience for an emerging technology brand.", technologies: ["Next.js", "TypeScript", "Tailwind CSS"], liveUrl: null, screenshots: ["/images/portfolio-1.png", "/images/about-1.png", "/images/portfolio-5.png"], caseStudy: { challenge: "Present an advanced product in a clear and credible way.", solution: "A structured, responsive interface with bold visuals and fast navigation.", result: "A polished digital experience ready for international prospects." } },
  { slug: "mobile-coin-app", title: "Mobile Coin View App", category: "Technology", imageUrl: "/images/portfolio-2.png", excerpt: "A data-focused interface with responsive dashboards and clear navigation.", technologies: ["React", "API", "Dashboard"], liveUrl: null, screenshots: ["/images/portfolio-2.png", "/images/portfolio-6.png", "/images/about-2.png"], caseStudy: { challenge: "Make complex data easier to scan on mobile devices.", solution: "A focused dashboard layout with reusable visual components.", result: "A cleaner user journey for daily monitoring." } },
  { slug: "security-analysis", title: "Analysis of Security", category: "Corporate", imageUrl: "/images/portfolio-3.png", excerpt: "A trust-driven corporate website for a technical security service.", technologies: ["Next.js", "Security", "SEO"], liveUrl: null, screenshots: ["/images/portfolio-3.png", "/images/about-1.png", "/images/portfolio-1.png"], caseStudy: { challenge: "Explain a specialized service without overwhelming visitors.", solution: "A conversion-focused architecture with concise technical messaging.", result: "A credible website prepared for qualified enquiries." } },
  { slug: "ecommerce-store", title: "eCommerce Website", category: "eCommerce", imageUrl: "/images/portfolio-4.png", excerpt: "A conversion-oriented online store experience for scalable product sales.", technologies: ["Next.js", "PostgreSQL", "Payments"], liveUrl: null, screenshots: ["/images/portfolio-4.png", "/images/portfolio-5.png", "/images/about-2.png"], caseStudy: { challenge: "Create a clearer path from product discovery to checkout.", solution: "Responsive product browsing and simplified conversion flows.", result: "A scalable store foundation ready for catalogue expansion." } },
  { slug: "responsive-design", title: "Responsive Design", category: "Personal", imageUrl: "/images/portfolio-5.png", excerpt: "A mobile-first portfolio concept with an elegant visual hierarchy.", technologies: ["Tailwind CSS", "UX", "Responsive UI"], liveUrl: null, screenshots: ["/images/portfolio-5.png", "/images/portfolio-2.png", "/images/about-1.png"], caseStudy: { challenge: "Keep a premium appearance across every device size.", solution: "A carefully spaced responsive system with strong typography.", result: "A consistent experience from mobile to desktop." } },
  { slug: "health-app", title: "App for Health", category: "Technology", imageUrl: "/images/portfolio-6.png", excerpt: "A modern dashboard concept focused on clarity and accessible information.", technologies: ["React", "Dashboard", "UI/UX"], liveUrl: null, screenshots: ["/images/portfolio-6.png", "/images/portfolio-3.png", "/images/about-2.png"], caseStudy: { challenge: "Organize health-related information in a calm interface.", solution: "Readable dashboards with a modular content structure.", result: "A reassuring digital product concept with room to grow." } },
]

export const defaultDemos = [
  { slug: "business-agency", title: "Business Agency Website", category: "Business Websites", imageUrl: "/images/portfolio-1.png", previewUrl: "#", liveUrl: "#" },
  { slug: "developer-portfolio", title: "Developer Portfolio", category: "Portfolio Websites", imageUrl: "/images/portfolio-2.png", previewUrl: "#", liveUrl: "#" },
  { slug: "modern-store", title: "Modern E-Commerce Store", category: "E-Commerce Websites", imageUrl: "/images/portfolio-4.png", previewUrl: "#", liveUrl: "#" },
  { slug: "daily-news", title: "Daily News Portal", category: "News Portals", imageUrl: "/images/portfolio-3.png", previewUrl: "#", liveUrl: "#" },
  { slug: "corporate-suite", title: "Corporate Company Website", category: "Corporate Websites", imageUrl: "/images/portfolio-5.png", previewUrl: "#", liveUrl: "#" },
  { slug: "campaign-landing", title: "Conversion Landing Page", category: "Landing Pages", imageUrl: "/images/portfolio-6.png", previewUrl: "#", liveUrl: "#" },
]

export const defaultTeamMembers = [
  { slug: "arif-hossain", name: "Arif Hossain", role: "Project Strategy", bio: "Coordinates planning, communication and delivery for digital projects.", imageUrl: "/images/team-1.svg", skills: ["Planning", "Communication", "Delivery"], experience: "Demo profile — replace from the admin panel.", email: null },
  { slug: "nusrat-jahan", name: "Nusrat Jahan", role: "Frontend Engineering", bio: "Builds responsive interfaces with a strong focus on usability and performance.", imageUrl: "/images/team-2.svg", skills: ["Next.js", "TypeScript", "Tailwind CSS"], experience: "Demo profile — replace from the admin panel.", email: null },
  { slug: "tanvir-ahmed", name: "Tanvir Ahmed", role: "Backend Engineering", bio: "Develops reliable APIs, database models and practical backend integrations.", imageUrl: "/images/team-3.svg", skills: ["PostgreSQL", "Prisma", "APIs"], experience: "Demo profile — replace from the admin panel.", email: null },
  { slug: "mahi-akter", name: "Mahi Akter", role: "UI/UX Design", bio: "Shapes premium visual systems that stay clear across desktop and mobile devices.", imageUrl: "/images/team-4.svg", skills: ["UI Design", "Responsive UX", "Accessibility"], experience: "Demo profile — replace from the admin panel.", email: null },
]

export const defaultPages = [
  { slug: "about-us", title: "About Us", excerpt: "Learn about IT Lab BD, our history, mission and values.", content: { heroTitle: "Technology built around your business goals.", heroDescription: "IT Lab BD helps companies create credible, fast and scalable digital experiences for local and international markets.", companyHistory: "IT Lab BD grew from a simple belief: a business website should look professional, load quickly and solve a real commercial problem. Our work combines design, engineering and ongoing support. From business websites to e-commerce and custom platforms, each project is planned with performance, security and future growth in mind.", mission: "Deliver dependable digital solutions that help clients grow with confidence.", coreValues: [{ title: "Practical innovation", text: "We choose modern technology that creates real business value." }, { title: "Reliable delivery", text: "Security, maintainability and clarity are part of the work, not add-ons." }, { title: "Long-term partnership", text: "We support clients beyond launch with honest technical guidance." }] } },
  { slug: "our-mission", title: "Our Mission", excerpt: "Discover the mission that guides IT Lab BD projects.", content: { heroTitle: "Building digital products that create practical business value.", heroDescription: "Our mission is to combine clarity, reliable engineering and measurable results.", imageUrl: "/images/about-1.png", body: "Our mission is to help businesses use technology with confidence. We design and build digital products that are clear, fast, secure and easy to maintain. Every project begins with a practical business objective and ends with a solution that can continue growing over time." } },
  { slug: "our-vision", title: "Our Vision", excerpt: "Learn how IT Lab BD approaches the future of digital business.", content: { heroTitle: "Making modern technology useful, accessible and sustainable.", heroDescription: "We want businesses of every size to benefit from well-designed digital tools.", imageUrl: "/images/about-2.png", body: "Our vision is a digital landscape where companies do not need to choose between premium design, dependable performance and maintainable technology. We aim to create products that feel modern today and remain useful tomorrow." } },
  { slug: "our-philosophy", title: "Our Philosophy", excerpt: "Explore the principles behind our design and engineering decisions.", content: { heroTitle: "Simple decisions, strong foundations and honest delivery.", heroDescription: "Our philosophy keeps each project focused on real business needs.", imageUrl: "/images/portfolio-5.png", body: "Our philosophy is simple: technology should solve problems instead of creating new ones. We prefer clear architecture, thoughtful interfaces and transparent communication. The goal is not unnecessary complexity. The goal is dependable progress." } },
  { slug: "our-strategy", title: "Our Strategy", excerpt: "See how IT Lab BD combines planning, design and engineering.", content: { heroTitle: "A focused strategy from discovery to long-term support.", heroDescription: "We connect business goals with design, development and continuous improvement.", imageUrl: "/images/portfolio-3.png", body: "Our strategy combines research, clear planning, responsive design, secure engineering and practical support. We build in stages, validate the important decisions early and keep each implementation ready for future growth." } },
  { slug: "our-team", title: "Our Team", excerpt: "Meet the IT Lab BD web development team.", content: { heroTitle: "A practical team for serious digital projects.", heroDescription: "Meet the people behind IT Lab BD. Demo member profiles can be replaced from the admin dashboard whenever your final team data is ready.", introduction: "A compact expert team can move faster, communicate better and stay focused on results." } },
  { slug: "contact-us", title: "Contact Us", excerpt: "Send your project requirements to IT Lab BD.", content: { heroTitle: "Tell us what you want to build.", heroDescription: "Share your project requirements and our team will get back to you with the next practical step.", formHeadline: "Have a quick question?", imageUrl: "/images/robot.png", imageEyebrow: "Let's build", imageTitle: "Turn your next idea into a fast, secure digital product." } },
]

export const defaultLogos = ["Databricks", "Amazon", "Trello", "Monzo", "OLA", "Walmart", "Contentful", "Inntel", "Dropbox", "Zetra", "Treehouse", "Bitcoin"]

export const defaultMenuItems = [
  { key: "home", label: "Home", href: "/", sortOrder: 10 },
  { key: "about", label: "About", href: "/about-us", sortOrder: 20 },
  { key: "about-us", parentKey: "about", label: "About Us", href: "/about-us", sortOrder: 10 },
  { key: "our-team", parentKey: "about", label: "Our Team", href: "/our-team", sortOrder: 20 },
  { key: "services", label: "Services", href: "/services", sortOrder: 30 },
  ...defaultServices.map((service, index) => ({ key: `service-${service.slug}`, parentKey: "services", label: service.title, href: `/services/${service.slug}`, sortOrder: (index + 1) * 10 })),
  { key: "demo", label: "Demo", href: "/demo", sortOrder: 40 },
  { key: "contact-us", label: "Contact Us", href: "/contact-us", sortOrder: 50 },
]
