import type { Metadata } from "next"
import Image from "next/image"
import { ExternalLink } from "lucide-react"
import { notFound } from "next/navigation"
import { PageHero } from "@/components/pages/page-hero"
import { PublicShell } from "@/components/pages/public-shell"
import { getProjectBySlug, getSeoMetadata } from "@/lib/cms"
function list(value:unknown){return Array.isArray(value)?value.map(String):[]}
function record(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{} as Record<string,unknown>}
export const dynamic="force-dynamic"
export const revalidate=0
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const project=await getProjectBySlug(slug);if(!project)return{title:"Portfolio project"};return getSeoMetadata(`/portfolio/${slug}`,{title:project.title,description:project.excerpt||`Explore the ${project.title} IT Lab BD case study.`})}
export default async function ProjectDetailPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const project=await getProjectBySlug(slug);if(!project)notFound();const screenshots=list(project.screenshots);const technologies=list(project.technologies);const caseStudy=record(project.caseStudy);return <PublicShell><PageHero eyebrow="Portfolio" title={project.title} description={project.excerpt||"A selected IT Lab BD digital project."} breadcrumbs={[{label:"Portfolio",href:"/portfolio"},{label:project.title}]} /><section className="py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><div className="grid gap-10 lg:grid-cols-[1.35fr_.65fr]"><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-lg"><Image src={project.imageUrl} alt={project.title} width={1400} height={1000} className="aspect-[7/5] w-full object-cover" priority /></div><aside className="rounded-[2rem] border border-slate-200 bg-slate-50 p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">Project Details</p><h2 className="mt-3 font-heading text-3xl font-bold">{project.title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{project.excerpt}</p><div className="mt-6 flex flex-wrap gap-2">{technologies.map(item=><span key={item} className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{item}</span>)}</div>{project.liveUrl&&<a href={project.liveUrl} target="_blank" rel="noreferrer" className="brand-button mt-7 inline-flex cursor-pointer items-center gap-2 rounded-xl px-5 py-3 text-sm font-bold text-white">Open live website<ExternalLink className="size-4" /></a>}</aside></div></div></section><section className="bg-slate-50 py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><h2 className="font-heading text-3xl font-bold md:text-5xl">Screenshots</h2><div className="mt-9 grid gap-6 md:grid-cols-3">{screenshots.map((src,index)=><div key={`${src}-${index}`} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Image src={src} alt={`${project.title} screenshot ${index+1}`} width={900} height={675} className="aspect-[4/3] w-full object-cover transition duration-700 hover:scale-105" /></div>)}</div><div className="mt-16"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">Case Study</p><h2 className="mt-3 font-heading text-3xl font-bold md:text-5xl">From challenge to practical result.</h2><div className="mt-9 grid gap-6 md:grid-cols-3">{[["Challenge",caseStudy.challenge],["Solution",caseStudy.solution],["Result",caseStudy.result]].map(([title,text])=><article key={String(title)} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h3 className="font-heading text-xl font-semibold">{String(title)}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{String(text||"Add this case study detail from the admin panel.")}</p></article>)}</div></div></div></section></PublicShell>}
