import type { Metadata } from "next"
import { HeartHandshake, Rocket, ShieldCheck } from "lucide-react"
import { PageHero } from "@/components/pages/page-hero"
import { PublicShell } from "@/components/pages/public-shell"
import { getPageContent, getSeoMetadata } from "@/lib/cms"
export const dynamic="force-dynamic"
export const revalidate=0
export async function generateMetadata():Promise<Metadata>{return getSeoMetadata("/about-us",{title:"About Us",description:"Learn about IT Lab BD, our history, mission and values."})}
type Value={title:string;text:string}
const icons=[Rocket,ShieldCheck,HeartHandshake]
export default async function AboutUsPage(){const page=await getPageContent("about-us");const content=(page?.content||{}) as Record<string,unknown>;const values=Array.isArray(content.coreValues)?content.coreValues as Value[]:[];return <PublicShell><PageHero eyebrow="About Us" title={String(content.heroTitle||"Technology built around your business goals.")} description={String(content.heroDescription||"IT Lab BD helps companies create credible, fast and scalable digital experiences.")} breadcrumbs={[{label:"About Us"}]} /><section className="py-20"><div className="mx-auto grid max-w-[1760px] gap-8 px-6 lg:grid-cols-[1.25fr_.75fr] lg:px-10"><article className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm md:p-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">Company History</p><h2 className="mt-3 font-heading text-3xl font-bold md:text-4xl">Built around practical digital progress.</h2><p className="mt-5 text-base leading-8 text-muted-foreground">{String(content.companyHistory||"")}</p></article><article className="rounded-3xl bg-blue-700 p-8 text-white shadow-lg md:p-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-sky-100">Mission</p><h2 className="mt-3 font-heading text-3xl font-bold">A clear goal for every project.</h2><p className="mt-5 text-base leading-8 text-white/85">{String(content.mission||"")}</p></article></div></section><section className="bg-slate-50 py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><h2 className="font-heading text-3xl font-bold md:text-5xl">Core Values</h2><div className="mt-9 grid gap-6 md:grid-cols-3">{values.map((value,index)=>{const Icon=icons[index%icons.length];return <article key={value.title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><span className="flex size-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-700"><Icon className="size-7" /></span><h3 className="mt-5 font-heading text-xl font-semibold">{value.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{value.text}</p></article>})}</div></div></section></PublicShell>}
