"use client"
import { FormEvent, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Save, Upload } from "lucide-react"
import { getCsrf } from "@/components/admin/csrf"
import { notifyCmsUpdated } from "@/components/admin/cms-updated"

type Settings = { site_name: string; logo_text: string; header_logo_mode: "text" | "image"; header_logo_image_url: string; footer_logo_mode: "text" | "image"; footer_logo_image_url: string; phone: string; email: string; address: string; topbar_message: string; twitter_url: string; facebook_url: string; linkedin_url: string }
const initial: Settings = { site_name: "IT LAB BD", logo_text: "it", header_logo_mode: "text", header_logo_image_url: "", footer_logo_mode: "text", footer_logo_image_url: "", phone: "", email: "", address: "", topbar_message: "Howdy, ITLABBD", twitter_url: "#", facebook_url: "#", linkedin_url: "#" }
export function BrandingSettingsEditor() {
  const router = useRouter()
  const [settings, setSettings] = useState<Settings>(initial)
  const [message, setMessage] = useState("")
  useEffect(() => { fetch("/api/admin/site-settings", { cache: "no-store" }).then(response => response.json()).then(data => setSettings({ ...initial, ...(data.settings || {}) })) }, [])
  function change<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings(current => ({ ...current, [key]: value })) }
  async function upload(key: "header_logo_image_url" | "footer_logo_image_url", file?: File) { if (!file) return; const csrf = await getCsrf(); const body = new FormData(); body.append("file", file); body.append("altText", key === "header_logo_image_url" ? "IT Lab BD header logo" : "IT Lab BD footer logo"); const response = await fetch("/api/admin/media/upload", { method: "POST", headers: { "x-csrf-token": csrf }, body }); const json = await response.json().catch(() => ({})); if (!response.ok) return setMessage(json.error || "Upload failed"); change(key, json.media?.url || json.item?.url || ""); setMessage("Logo uploaded. Save settings to publish it.") }
  async function submit(event: FormEvent) { event.preventDefault(); const csrf = await getCsrf(); const response = await fetch("/api/admin/site-settings", { method: "PUT", headers: { "content-type": "application/json", "x-csrf-token": csrf }, body: JSON.stringify(settings) }); const json = await response.json().catch(() => ({})); if (!response.ok) return setMessage(json.error || "Unable to save settings."); notifyCmsUpdated(); router.refresh(); setMessage("Website settings saved. Database committed and frontend cache invalidated immediately.") }
  return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Website Settings</p><h1 className="mt-1 font-heading text-3xl font-bold">Branding, independent logos and contact details</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">The header and footer logos are controlled independently. Choose a text logo or upload a separate image for each area.</p><form onSubmit={submit} className="mt-7 grid max-w-5xl gap-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2 md:p-8"><Input label="Website name" value={settings.site_name} onChange={value => change("site_name", value)} /><Input label="Text logo initials" value={settings.logo_text} onChange={value => change("logo_text", value)} /><LogoControl title="Header logo" mode={settings.header_logo_mode} imageUrl={settings.header_logo_image_url} changeMode={value => change("header_logo_mode", value)} changeUrl={value => change("header_logo_image_url", value)} upload={file => upload("header_logo_image_url", file)} /><LogoControl title="Footer logo" mode={settings.footer_logo_mode} imageUrl={settings.footer_logo_image_url} changeMode={value => change("footer_logo_mode", value)} changeUrl={value => change("footer_logo_image_url", value)} upload={file => upload("footer_logo_image_url", file)} /><Input label="Top bar message" value={settings.topbar_message} onChange={value => change("topbar_message", value)} /><Input label="Phone number" value={settings.phone} onChange={value => change("phone", value)} /><Input label="Email address" type="email" value={settings.email} onChange={value => change("email", value)} /><Input label="Address" value={settings.address} onChange={value => change("address", value)} /><Input label="Twitter URL" value={settings.twitter_url} onChange={value => change("twitter_url", value)} /><Input label="Facebook URL" value={settings.facebook_url} onChange={value => change("facebook_url", value)} /><Input label="LinkedIn URL" value={settings.linkedin_url} onChange={value => change("linkedin_url", value)} /><div className="md:col-span-2"><button className="brand-button inline-flex cursor-pointer items-center gap-2 rounded-xl px-5 py-3 text-sm font-bold text-white"><Save className="size-4" />Save website settings</button>{message && <p className="mt-4 text-sm font-semibold text-blue-700">{message}</p>}</div></form></div>
}
function LogoControl({ title, mode, imageUrl, changeMode, changeUrl, upload }: { title: string; mode: "text" | "image"; imageUrl: string; changeMode: (value: "text" | "image") => void; changeUrl: (value: string) => void; upload: (file?: File) => void }) { return <div className="grid gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-5 md:col-span-2"><h2 className="font-heading text-lg font-bold">{title}</h2><div className="grid gap-4 md:grid-cols-2"><Select label="Logo type" value={mode} onChange={value => changeMode(value as "text" | "image")} /><label className="grid gap-2 text-sm font-semibold">Uploaded image<div className="flex gap-2"><input value={imageUrl} onChange={event => changeUrl(event.target.value)} placeholder="/uploads/company-logo.webp" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" /><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700 transition hover:bg-blue-100"><Upload className="size-4" />Upload<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={event => upload(event.target.files?.[0])} /></label></div></label></div></div> }
function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2 text-sm font-semibold">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" /></label> }
function Select({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-2 text-sm font-semibold">{label}<select value={value} onChange={event => onChange(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200"><option value="text">Text logo / site name</option><option value="image">Uploaded image logo</option></select></label> }
