"use client"

import Link from "next/link"
import { FormEvent, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Plus, Save, Trash2, Upload } from "lucide-react"
import { getCsrf } from "@/components/admin/csrf"
import { notifyCmsUpdated } from "@/components/admin/cms-updated"

type Section = { id: string; type: string; title: string; enabled: boolean; sortOrder: number; content: Record<string, unknown> }
type Feature = { label: string; icon: string }
type CounterItem = { label: string; value: number; icon?: string }
type AboutBlock = { title: string; text: string; imageUrl: string; href: string }
type Platform = { name: string; badge: string; description: string; imageUrl: string; href: string }
const labels: Record<string, string> = { HERO: "Hero Section", ABOUT: "About Section", COUNTERS: "Counter Section", SERVICES: "Services Section", PLATFORMS: "Global Platforms", WHAT_WE_DO: "What We Do", PORTFOLIO: "Portfolio Section", TESTIMONIALS: "Testimonials Section", TRUSTED_COMPANIES: "Trusted Companies", CONTACT: "Contact Section" }
const iconHelp = "Examples: ShoppingCart, Briefcase, Building2, User, Code2, Newspaper, Server, Search, Home, Store, Users, Award"
function string(value: unknown) { return value == null ? "" : String(value) }
function list<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : [] }

export function HomeSectionEditor({ sectionType }: { sectionType: string }) {
  const router = useRouter()
  const type = sectionType.toUpperCase().replaceAll("-", "_")
  const [section, setSection] = useState<Section | null>(null)
  const [message, setMessage] = useState("")
  useEffect(() => { fetch("/api/admin/homepage-sections", { cache: "no-store" }).then(response => response.json()).then(data => setSection((data.items || []).find((item: Section) => item.type === type) || null)) }, [type])
  function updateContent(key: string, value: unknown) { if (section) setSection({ ...section, content: { ...section.content, [key]: value } }) }
  function updateArray<T extends Record<string, unknown>>(key: string, index: number, field: keyof T, value: unknown) { const rows = [...list<T>(section?.content[key])]; rows[index] = { ...rows[index], [field]: value }; updateContent(key, rows) }
  function addArray<T>(key: string, row: T) { updateContent(key, [...list<T>(section?.content[key]), row]) }
  function removeArray<T>(key: string, index: number) { updateContent(key, list<T>(section?.content[key]).filter((_, position) => position !== index)) }
  async function uploadImage(setter: (url: string) => void, file?: File) { if (!file) return; const csrf = await getCsrf(); const form = new FormData(); form.append("file", file); form.append("altText", `${labels[type] || type} image`); const response = await fetch("/api/admin/media/upload", { method: "POST", headers: { "x-csrf-token": csrf }, body: form }); const json = await response.json().catch(() => ({})); if (!response.ok) return setMessage(json.error || "Image upload failed."); setter(json.media?.url || json.item?.url || json.url); setMessage("Image uploaded. Save the section to publish the change.") }
  async function save(event: FormEvent) { event.preventDefault(); if (!section) return; const csrf = await getCsrf(); const response = await fetch(`/api/admin/homepage-sections/${section.id}`, { method: "PUT", headers: { "content-type": "application/json", "x-csrf-token": csrf }, body: JSON.stringify(section) }); const json = await response.json().catch(() => ({})); if (!response.ok) return setMessage(json.error || "Unable to save this section."); notifyCmsUpdated(); router.refresh(); setMessage("Saved successfully. Database committed and frontend cache invalidated immediately.") }
  if (!section) return <p className="text-muted-foreground">Loading section editor...</p>
  const content = section.content || {}
  return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Home Page CMS</p><h1 className="mt-1 font-heading text-3xl font-bold">{labels[type] || section.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Every visible field in this section can be updated here. Images may be uploaded directly without editing code or JSON.</p><form onSubmit={save} className="mt-7 max-w-5xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-5 md:grid-cols-2"><Input label="Admin label" value={section.title} onChange={value => setSection({ ...section, title: value })} /><Input label="Sort order" type="number" value={String(section.sortOrder)} onChange={value => setSection({ ...section, sortOrder: Number(value || 0) })} />
    {type === "HERO" && <HeroFields content={content} update={updateContent} upload={uploadImage} updateArray={updateArray} addArray={addArray} removeArray={removeArray} />}
    {type === "ABOUT" && <AboutFields content={content} update={updateContent} upload={uploadImage} updateArray={updateArray} addArray={addArray} removeArray={removeArray} />}
    {type === "COUNTERS" && <CounterFields content={content} updateArray={updateArray} addArray={addArray} removeArray={removeArray} />}
    {type === "SERVICES" && <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => updateContent("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => updateContent("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => updateContent("subtitle", value)} /><Manager href="/admin/services" label="Manage service cards, icons, images and View More links" /></>}
    {type === "PLATFORMS" && <PlatformFields content={content} update={updateContent} upload={uploadImage} updateArray={updateArray} addArray={addArray} removeArray={removeArray} />}
    {type === "WHAT_WE_DO" && <WhatFields content={content} update={updateContent} updateArray={updateArray} addArray={addArray} removeArray={removeArray} />}
    {type === "PORTFOLIO" && <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => updateContent("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => updateContent("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => updateContent("subtitle", value)} /><Input label="Bottom button label" value={string(content.buttonLabel)} onChange={value => updateContent("buttonLabel", value)} /><Input label="Bottom button URL" value={string(content.buttonUrl)} onChange={value => updateContent("buttonUrl", value)} /><Manager href="/admin/portfolios" label="Manage portfolio cards, detail links and live URLs" /></>}
    {type === "TESTIMONIALS" && <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => updateContent("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => updateContent("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => updateContent("subtitle", value)} /><Input label="Testimonials displayed at once" type="number" value={string(content.displayCount || 3)} onChange={value => updateContent("displayCount", Math.max(1, Number(value || 3)))} /><Manager href="/admin/testimonials" label="Manage client images, names, reviews, ratings and positions" /></>}
    {type === "TRUSTED_COMPANIES" && <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => updateContent("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => updateContent("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => updateContent("subtitle", value)} /><Manager href="/admin/logos" label="Add, edit or remove trusted-company logos" /></>}
    {type === "CONTACT" && <ContactFields content={content} update={updateContent} upload={uploadImage} />}
    <label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-semibold md:col-span-2"><input type="checkbox" checked={section.enabled} onChange={event => setSection({ ...section, enabled: event.target.checked })} className="size-4" />Display this section</label></div><button className="brand-button mt-6 inline-flex cursor-pointer items-center gap-2 rounded-xl px-5 py-3 text-sm font-bold text-white"><Save className="size-4" />Save section</button>{message && <p className="mt-4 text-sm font-semibold text-blue-700">{message}</p>}</form></div>
}

function HeroFields({ content, update, upload, updateArray, addArray, removeArray }: any) { const rows = list<Feature>(content.features); return <><Input label="Small heading" value={string(content.eyebrow)} onChange={value => update("eyebrow", value)} /><Input label="Main title" value={string(content.headline)} onChange={value => update("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => update("subtitle", value)} /><ImageInput label="Hero background image" value={string(content.imageUrl)} onChange={value => update("imageUrl", value)} upload={file => upload((url: string) => update("imageUrl", url), file)} /><RepeaterTitle title="Hero feature items" help={`Add, remove and edit icon-and-text pills. ${iconHelp}`} onAdd={() => addArray("features", { label: "New feature", icon: "Code2" })} />{rows.map((row, index) => <Row key={index}><Input label={`Feature ${index + 1} text`} value={row.label} onChange={value => updateArray("features", index, "label", value)} /><Input label="Icon name" value={row.icon} onChange={value => updateArray("features", index, "icon", value)} /><Remove onClick={() => removeArray("features", index)} /></Row>)}</> }
function AboutFields({ content, update, upload, updateArray, addArray, removeArray }: any) { const rows = list<AboutBlock>(content.blocks); return <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => update("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => update("headline", value)} /><Area label="Introduction" value={string(content.intro)} onChange={value => update("intro", value)} /><Area label="Mission paragraph" value={string(content.mission)} onChange={value => update("mission", value)} /><Area label="Closing paragraph" value={string(content.closing)} onChange={value => update("closing", value)} /><RepeaterTitle title="Image overlay cards" help="Each card has an editable image, title, overlay text and destination link." onAdd={() => addArray("blocks", { title: "New block", text: "", imageUrl: "/images/about-1.png", href: "/about-us" })} />{rows.map((row, index) => <Row key={index}><Input label={`Block ${index + 1} title`} value={row.title} onChange={value => updateArray("blocks", index, "title", value)} /><Input label="Destination URL" value={row.href || "/about-us"} onChange={value => updateArray("blocks", index, "href", value)} /><Area label="Overlay text" value={row.text} onChange={value => updateArray("blocks", index, "text", value)} small /><ImageInput label="Background image" value={row.imageUrl} onChange={value => updateArray("blocks", index, "imageUrl", value)} upload={file => upload((url: string) => updateArray("blocks", index, "imageUrl", url), file)} /><Remove onClick={() => removeArray("blocks", index)} /></Row>)}</> }
function CounterFields({ content, updateArray, addArray, removeArray }: any) { const rows = list<CounterItem>(content.counters); return <><RepeaterTitle title="Counter items" help={`Add 4, 5 or more counters. The public grid adapts automatically. ${iconHelp}`} onAdd={() => addArray("counters", { label: "New counter", value: 0, icon: "Award" })} />{rows.map((row, index) => <Row key={index}><Input label={`Counter ${index + 1} label`} value={row.label} onChange={value => updateArray("counters", index, "label", value)} /><Input label="Number" type="number" value={String(row.value ?? 0)} onChange={value => updateArray("counters", index, "value", Number(value || 0))} /><Input label="Icon name" value={row.icon || "Award"} onChange={value => updateArray("counters", index, "icon", value)} /><Remove onClick={() => removeArray("counters", index)} /></Row>)}</> }
function PlatformFields({ content, update, upload, updateArray, addArray, removeArray }: any) { const rows = list<Platform>(content.platforms); return <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => update("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => update("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => update("subtitle", value)} /><RepeaterTitle title="Marketplace platforms" help="Manage platform logos or profile images, titles and clickable external profile URLs." onAdd={() => addArray("platforms", { name: "New platform", badge: "Global marketplace", description: "", imageUrl: "/images/platform-themeforest.svg", href: "#" })} />{rows.map((row, index) => <Row key={index}><Input label={`Platform ${index + 1} name`} value={row.name} onChange={value => updateArray("platforms", index, "name", value)} /><Input label="Badge" value={row.badge} onChange={value => updateArray("platforms", index, "badge", value)} /><Input label="Profile URL" value={row.href} onChange={value => updateArray("platforms", index, "href", value)} /><Area label="Description" value={row.description} onChange={value => updateArray("platforms", index, "description", value)} small /><ImageInput label="Logo or profile image" value={row.imageUrl} onChange={value => updateArray("platforms", index, "imageUrl", value)} upload={file => upload((url: string) => updateArray("platforms", index, "imageUrl", url), file)} /><Remove onClick={() => removeArray("platforms", index)} /></Row>)}</> }
function WhatFields({ content, update, updateArray, addArray, removeArray }: any) { const rows = list<Feature>(content.items); return <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => update("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => update("headline", value)} /><Area label="Subtitle" value={string(content.subtitle)} onChange={value => update("subtitle", value)} /><RepeaterTitle title="Industry items" help={`Edit every label and icon. ${iconHelp}`} onAdd={() => addArray("items", { label: "New item", icon: "Code2" })} />{rows.map((row, index) => <Row key={index}><Input label={`Item ${index + 1} text`} value={row.label} onChange={value => updateArray("items", index, "label", value)} /><Input label="Icon name" value={row.icon} onChange={value => updateArray("items", index, "icon", value)} /><Remove onClick={() => removeArray("items", index)} /></Row>)}</> }
function ContactFields({ content, update, upload }: any) { return <><Input label="Eyebrow" value={string(content.eyebrow)} onChange={value => update("eyebrow", value)} /><Input label="Public headline" value={string(content.headline)} onChange={value => update("headline", value)} /><ImageInput label="Contact image" value={string(content.imageUrl)} onChange={value => update("imageUrl", value)} upload={file => upload((url: string) => update("imageUrl", url), file)} /></> }
function Manager({ href, label }: { href: string; label: string }) { return <div className="rounded-2xl border border-blue-100 bg-blue-50 p-5 md:col-span-2"><p className="text-sm font-semibold text-blue-950">{label}</p><Link href={href} className="mt-3 inline-flex cursor-pointer rounded-xl bg-white px-4 py-2 text-sm font-bold text-blue-700 shadow-sm transition hover:bg-blue-100">Open content manager</Link></div> }
function RepeaterTitle({ title, help, onAdd }: { title: string; help: string; onAdd: () => void }) { return <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 md:col-span-2"><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{help}</p></div><button type="button" onClick={onAdd} className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-blue-100 bg-white px-3 py-2 text-xs font-bold text-blue-700 transition hover:bg-blue-50"><Plus className="size-4" />Add item</button></div> }
function Row({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 md:col-span-2 md:grid-cols-2">{children}</div> }
function Remove({ onClick }: { onClick: () => void }) { return <button type="button" onClick={onClick} className="inline-flex w-fit cursor-pointer items-center gap-2 rounded-xl border border-red-100 bg-white px-3 py-2 text-xs font-bold text-red-600 transition hover:bg-red-50"><Trash2 className="size-4" />Remove item</button> }
function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2 text-sm font-semibold">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} onKeyDown={event => { if (event.key === "Enter") event.stopPropagation() }} className="rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" /></label> }
function Area({ label, value, onChange, help, small = false }: { label: string; value: string; onChange: (value: string) => void; help?: string; small?: boolean }) { return <label className="grid gap-2 text-sm font-semibold md:col-span-2">{label}<textarea rows={small ? 3 : 5} value={value} onChange={event => onChange(event.target.value)} onKeyDown={event => { if (event.key === "Enter") event.stopPropagation() }} className="rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" />{help && <span className="text-xs font-normal text-muted-foreground">{help}</span>}</label> }
function ImageInput({ label, value, onChange, upload }: { label: string; value: string; onChange: (value: string) => void; upload: (file?: File) => void }) { return <label className="grid gap-2 text-sm font-semibold md:col-span-2">{label}<div className="flex flex-wrap gap-2"><input value={value} onChange={event => onChange(event.target.value)} placeholder="/uploads/image.webp" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" /><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700 transition hover:bg-blue-100"><Upload className="size-4" />Upload<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={event => upload(event.target.files?.[0])} /></label></div></label> }
