"use client"
import { FormEvent, useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Save, Upload } from "lucide-react"
import { getCsrf } from "@/components/admin/csrf"
import { notifyCmsUpdated } from "@/components/admin/cms-updated"
type Page = { id: string; slug: string; title: string; excerpt?: string | null; published: boolean; content: Record<string, unknown> }
function valueText(value: unknown) { return value === null || value === undefined ? "" : String(value) }
function valuesText(value: unknown) { return Array.isArray(value) ? value.map((item: any) => `${item.title || ""} | ${item.text || ""}`).join("\n") : "" }
function values(value: string) { return value.split("\n").map(line => { const [title, ...rest] = line.split("|"); return { title: title.trim(), text: rest.join("|").trim() } }).filter(item => item.title) }
const detailPages = new Set(["our-mission", "our-vision", "our-philosophy", "our-strategy"])
export function PageContentEditor({ slug }: { slug: string }) {
  const router = useRouter()
  const [page, setPage] = useState<Page | null>(null)
  const [message, setMessage] = useState("")
  useEffect(() => { fetch("/api/admin/pages", { cache: "no-store" }).then(r => r.json()).then(data => setPage((data.items || []).find((item: Page) => item.slug === slug) || null)) }, [slug])
  if (!page) return <p className="text-muted-foreground">Loading page editor...</p>
  const currentPage = page
  const setContent = (key: string, value: unknown) => setPage({ ...currentPage, content: { ...currentPage.content, [key]: value } })
  async function save(event: FormEvent) { event.preventDefault(); const csrf = await getCsrf(); const response = await fetch(`/api/admin/pages/${currentPage.id}`, { method: "PUT", headers: { "content-type": "application/json", "x-csrf-token": csrf }, body: JSON.stringify(page) }); const json = await response.json().catch(() => ({})); if (!response.ok) return setMessage(json.error || "Unable to save this page."); notifyCmsUpdated(); router.refresh(); setMessage("Saved successfully. Database committed and frontend cache invalidated immediately.") }
  async function uploadImage(key: string, file?: File) { if (!file) return; const csrf = await getCsrf(); const form = new FormData(); form.append("file", file); form.append("altText", `${currentPage.title} image`); const response = await fetch("/api/admin/media/upload", { method: "POST", headers: { "x-csrf-token": csrf }, body: form }); const json = await response.json().catch(() => ({})); if (!response.ok) return setMessage(json.error || "Upload failed."); setContent(key, json.media?.url || json.item?.url || json.url); setMessage("Image uploaded. Save the page to publish the change.") }
  return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Page CMS</p><h1 className="mt-1 font-heading text-3xl font-bold">{page.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Edit the public page content below. You do not need to modify JSON.</p><form onSubmit={save} className="mt-7 max-w-4xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-5"><Input label="Hero title" value={valueText(page.content.heroTitle)} onChange={value => setContent("heroTitle", value)} /><Area label="Hero description" value={valueText(page.content.heroDescription)} onChange={value => setContent("heroDescription", value)} />{detailPages.has(slug) && <><ImageInput label="Main page image" value={valueText(page.content.imageUrl)} onChange={value => setContent("imageUrl", value)} upload={file => uploadImage("imageUrl", file)} /><Area label="Content block" value={valueText(page.content.body)} onChange={value => setContent("body", value)} /></>}{slug === "about-us" && <><Area label="Company history" value={valueText(page.content.companyHistory)} onChange={value => setContent("companyHistory", value)} /><Area label="Mission" value={valueText(page.content.mission)} onChange={value => setContent("mission", value)} /><Area label="Core values" value={valuesText(page.content.coreValues)} onChange={value => setContent("coreValues", values(value))} help="One value per line: Title | Description" /></>}{slug === "our-team" && <Area label="Team introduction" value={valueText(page.content.introduction)} onChange={value => setContent("introduction", value)} />}{slug === "contact-us" && <><Input label="Contact form headline" value={valueText(page.content.formHeadline)} onChange={value => setContent("formHeadline", value)} /><ImageInput label="Contact image" value={valueText(page.content.imageUrl)} onChange={value => setContent("imageUrl", value)} upload={file => uploadImage("imageUrl", file)} /><Input label="Image small heading" value={valueText(page.content.imageEyebrow)} onChange={value => setContent("imageEyebrow", value)} /><Area label="Image main text" value={valueText(page.content.imageTitle)} onChange={value => setContent("imageTitle", value)} /></>}<label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-semibold"><input type="checkbox" checked={page.published} onChange={event => setPage({ ...page, published: event.target.checked })} className="size-4" />Published</label></div><button className="brand-button mt-6 inline-flex cursor-pointer items-center gap-2 rounded-xl px-5 py-3 text-sm font-bold text-white"><Save className="size-4" />Save page</button>{message && <p className="mt-4 text-sm font-semibold text-blue-700">{message}</p>}</form></div>
}
function Input({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-2 text-sm font-semibold">{label}<input value={value} onChange={event => onChange(event.target.value)} onKeyDown={event => { if (event.key === "Enter") event.stopPropagation() }} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" /></label> }
function Area({ label, value, onChange, help }: { label: string; value: string; onChange: (value: string) => void; help?: string }) { return <label className="grid gap-2 text-sm font-semibold">{label}<textarea rows={5} value={value} onChange={event => onChange(event.target.value)} onKeyDown={event => { if (event.key === "Enter") event.stopPropagation() }} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" />{help && <span className="text-xs font-normal text-muted-foreground">{help}</span>}</label> }
function ImageInput({ label, value, onChange, upload }: { label: string; value: string; onChange: (value: string) => void; upload: (file?: File) => void }) { return <label className="grid gap-2 text-sm font-semibold">{label}<div className="flex flex-wrap gap-2"><input value={value} onChange={event => onChange(event.target.value)} onKeyDown={event => { if (event.key === "Enter") event.stopPropagation() }} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-200" /><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700 transition hover:bg-blue-100"><Upload className="size-4" />Upload<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={event => upload(event.target.files?.[0])} /></label></div></label> }
