import type { Metadata } from "next"
import Image from "next/image"
import { Mail } from "lucide-react"
import { PageHero } from "@/components/pages/page-hero"
import { PublicShell } from "@/components/pages/public-shell"
import { getPageContent, getSeoMetadata, getTeamMembers } from "@/lib/cms"
export const dynamic="force-dynamic"
export const revalidate=0
export async function generateMetadata():Promise<Metadata>{return getSeoMetadata("/our-team",{title:"Our Team",description:"Meet the IT Lab BD web development team."})}
function list(value:unknown){return Array.isArray(value)?value.map(String):[]}
export default async function TeamPage(){const [page,members]=await Promise.all([getPageContent("our-team"),getTeamMembers()]);const content=(page?.content||{}) as Record<string,unknown>;return <PublicShell><PageHero eyebrow="Our Team" title={String(content.heroTitle||"A practical team for serious digital projects.")} description={String(content.heroDescription||"Meet the people behind IT Lab BD.")} breadcrumbs={[{label:"About Us",href:"/about-us"},{label:"Our Team"}]} /><section className="py-20"><div className="mx-auto max-w-[1760px] px-6 lg:px-10"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-700">Team Introduction</p><h2 className="mt-3 font-heading text-3xl font-bold md:text-5xl">The people behind the work.</h2><p className="mt-4 text-base leading-relaxed text-muted-foreground">{String(content.introduction||"")}</p></div><div className="mt-10 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{members.map((member:any)=><article key={member.slug} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-2 hover:border-blue-200 hover:shadow-xl"><div className="overflow-hidden bg-blue-50"><Image src={member.imageUrl} width={640} height={720} alt={member.name} className="aspect-[8/9] w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{member.role}</p><h2 className="mt-2 font-heading text-2xl font-semibold">{member.name}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{member.bio}</p><div className="mt-4 flex flex-wrap gap-2">{list(member.skills).map(skill=><span key={skill} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{skill}</span>)}</div>{member.email&&<a className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700" href={`mailto:${member.email}`}><Mail className="size-4" />Contact</a>}</div></article>)}</div></div></section></PublicShell>}
